name: Compilation Test

on:
  push:
    branches:
      - feature_1546_ci_testing
    paths-ignore:
      - 'met/docs/**'

jobs:

  compile:
    name: Compile MET
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Compile MET in Docker
        run: .github/jobs/build_docker_image.sh
        env:
          SOURCE_BRANCH: ${GITHUB_REF#"refs/heads/"}
          MET_BASE_IMAGE: minimum
