name: Compilation Test

on:
  push:
    branches:
      - feature_1546_ci_testing
    paths-ignore:
      - 'met/docs/**'

jobs:

  compile:
    name: Compile MET
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get branch name
        id: get_branch_name
        run: echo ::set-output name=branch_name::${GITHUB_REF#"refs/heads/"}

      - name: Compile MET in Docker
        run: .github/jobs/build_docker_image.sh
        env:
          SOURCE_BRANCH: ${{ steps.get_branch_name.outputs.branch_name }}
          MET_BASE_IMAGE: minimum
