name: Compilation Test

# Test that compilation succeeds
# for feature_ and bugfix_ branches
# when file(s) under met/src have changed

on:
  push:
    branches:
      - 'feature_*'
      - 'bugfix_*'
    paths:
      - 'met/src/**'

jobs:

  compile:
    name: Compile MET
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set job controls
        id: job_status
        run: .github/jobs/set_job_controls.sh
        env:
          commit_msg: ${{ github.event.head_commit.message }}

      - name: Get branch name
        id: get_branch_name
        run: echo ::set-output name=branch_name::${GITHUB_REF#"refs/heads/"}

      - name: Compile MET in Docker
        run: .github/jobs/build_docker_image.sh
        if: ${{ steps.job_status.outputs.run_compile == 'true' }}
        env:
          SOURCE_BRANCH: ${{ steps.get_branch_name.outputs.branch_name }}
          MET_BASE_IMAGE: minimum

      - name: Upload logs as artifact
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: build_log
          path: docker_build.log
          if-no-files-found: ignore
